import Navbar from '../components/Navbar'
import './globals.css'
import Link from 'next/link'
import Footer from '@/components/Footer'

export const metadata = {
  title: 'Exercise Web Wildan',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <div>
          <Navbar />
        </div>
        <div className='p-8 bg-gray-100 min-h-screen text-gray-800 scrollbar '>
          {children}
        </div>
        <div>
          <Footer />
        </div>
      </body>
    </html>
  )
}
